Fixes #27066 - Corrects message on content source
Given a host group, and an invalid update involving content source,
For example:
  hg.update(:content_source => "", :kickstart_repository_id => 12)

This gave an error along the lines of
ArgumentError: tried to flatten recursive array

This was because of error message involving content source
The code did something like
hg.errors.add(:base, hg.errors.add(:base, "select content source"))

This commit fixes that error